### ISSUE TITLE
Could not load cppyy_backend library, details:\n%s?

### ISSUE THREAD

**Issue by NiKeYiGuN** [wlav/cppyy#178]
raise RuntimeError("could not load cppyy_backend library, details:\n%s" %
RuntimeError: could not load cppyy_backend library, details:
  Could not find module 'libcppyy_backend.cp38-win_amd64.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
  [WinError 1114] 动态链接库(DLL)初始化例程失败。
  Could not find module 'libcppyy_backend.dll' (or one of its dependencies). Try using the full path with constructor syntax.
  Could not find module 'C:\GIT\mymeep\venv\lib\site-packages\cppyy_backend\lib\libcppyy_backend.cp38-win_amd64.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
python-BaseException

**Comment by wlav** [comment]
Does the library exist on your system in the paths where `cppyy` is looking for it? I'd figure it exists, as "[WinError 1114] 动态链接库(DLL)初始化例程失败。" apparently translates as "[WinError 1114] Dynamic Link Library (DLL) initialization routine failed." suggesting that the library is found, but can not be loaded.

This being Windows: the library it found is 64b. Is the Python interpreter used also 64b?

**Comment by NiKeYiGuN** [comment]
yes,both the library and the Python interpreter are 64b，This error disappeared after I update cppyy  from 2.4.1 to 3.0.0.

**Comment by wlav** [comment]
On Windows, I'd expect problems with 2.4.1 for recent versions of MSVC as MSVC dropped support for Clang9 (on which 2.4 is based) about a year ago. However, I would expect that to manifest itself differently.

**Comment by N-Coder** [comment]
I had a similar issue when trying to use debug instead of release builds of my library on Windows, maybe that is the issue here too?

**Comment by N-Coder** [comment]
Hm, I'm now also getting this issue on GitHub Actions with an unmodified latest cppyy failing to load its backend:
https://github.com/ogdf/ogdf-wheel/actions/runs/8535679388/job/23382829735

**Comment by wlav** [comment]
Did this just start with a recent cppyy upgrade or did it appear with a chance of compilers on the action build machine?

My best guess is a mismatch of C++ versions. The offending code is protected with a preprocessor define `#if _HAS_CXX20`: https://github.com/light-tech/MSCpp/blob/master/include/msvc/type_traits#L1273

Can you set the `CLING_REBUILD_PCH` envar to force rebuilding of the PCH? (The standard chosen isn't part of the PCH name as in principle, it's fixed at installation time, so if there's somehow a standards change, it won't rebuild the PCH automatically.)

**Comment by N-Coder** [comment]
This issue already appeared [5 months ago](https://github.com/ogdf/ogdf-wheel/actions/runs/6901734211/job/18777378036) (unfortunately the logs are already gone, but I remember they looked pretty similar to what they look like on the more recent run). The CI isn't caching anything and installs freshly from a clean state, so there should also be no stale info after a standards change. Setting the env var unfortunately [didn't help](https://github.com/ogdf/ogdf-wheel/actions/runs/8565758360/job/23474484940).

**Comment by wlav** [comment]
Is it possible to downgrade to C++17 by setting the envar `STDCXX=17` at installation time? I checked and release 3.1.x is the only release where C++20 is enabled by default on Windows. Prior releases stick to C++17 or older.

**Comment by N-Coder** [comment]
Still doesn't work, although the errors now look [very different](https://github.com/ogdf/ogdf-wheel/actions/runs/8650504039/job/23719421736#step:7:32). We now have "failed to materialize symbols", both for things in the stdlib and within my library. [Previously](https://github.com/ogdf/ogdf-wheel/actions/runs/8565758360/job/23474484940#step:7:435) we had some parse error (MSVC\14.39.33519\include\type_traits:1394:5: error: expected a type) together with the dll not loading ([WinError 1114] A dynamic link library (DLL) initialization routine failed). Downgrading to cppyy 3.0 also [doesn't help](https://github.com/ogdf/ogdf-wheel/actions/runs/8650542285/job/23719518257). Regarding the parse error, I recently had something [remotely similar](https://github.com/ogdf/ogdf/actions/runs/8497960954/job/23277150847#step:5:220) because I mixed up the [order of some windows headers](https://stackoverflow.com/questions/52367594/why-does-changing-the-order-of-including-psapi-h-gives-compilation-errosindent) (but probably unrelated to C++ 20).

**Comment by wlav** [comment]
It's very concerning that the change of C++ standard used for Cling would make such a difference. :(

Interesting though that this is the first time that the "failed to materialize symbols" error occurs on another platform than some versions of Linux. There, the issue had to do with initializers in headers that Clang has trouble with, but I'd expect less, not more, of those when lowering the standard version.

`WINAPI` not being defined sounds familiar, but I can't find it.

As for the order, I'm wondering whether perhaps `Windows.h` should be added to the PCH (it's not, currently, included explicitly, but also not implicitly AFAIK).

**Comment by N-Coder** [comment]
As already promised [here](https://github.com/wlav/cppyy/issues/175#issuecomment-1811511573), I set up a GitHub Actions workflow for testing cppyy on different platforms at [N-Coder/cppyy-ci](https://github.com/N-Coder/cppyy-ci/actions/workflows/test.yml). Different env vars can be injected and versions of all the different cppyy packages can be selected (or the code from the github master branches can be used, which currently is the default). A manual trigger from the CLI looks like the following, but this can also be done through the web interface:
```
gh workflow run test.yml --field 'env=STDCXX=17\nCLING_REBUILD_PCH=1' --field 'ver-cppyy=3.1.2' --field 'ver-CPyCppyy=>0' --field 'ver-cppyy-backend=>0' --field 'ver-cppyy-cling=>0'
```
The `>0` is just to specify some non-empty pip version specifier so that the nightly version isn't taken by default.

Here, I get similar problems as before that again differ depending on whether I [set](https://github.com/N-Coder/cppyy-ci/actions/runs/8673273233/job/23784451811#step:19:45) `STDCXX=17` or [not](https://github.com/N-Coder/cppyy-ci/actions/runs/8673305664/job/23784524509#step:16:11). Unfortunately, I didn't find a way of injecting a `Windows.h` import at the right place. So, feel free to play around with this if you have time. You can also simply copy it for the official cppyy repo if that helps.

**Comment by N-Coder** [comment]
I now also get failures when importing cppyy on my Windows desktop:
```
>>> import cppyy
In file included from input_line_3:38:
In file included from C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include\cassert:9:
In file included from C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\ucrt\assert.h:12:
C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\ucrt\corecrt.h:260:12: error: redefinition of '_CrtEnableIf<true, _Ty>'
    struct _CrtEnableIf<true, _Ty>
           ^~~~~~~~~~~~~~~~~~~~~~~
C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt\corecrt.h:205:12: note: previous definition is here
    struct _CrtEnableIf<true, _Ty>
           ^
In file included from input_line_3:38:
In file included from C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include\cassert:9:
In file included from C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\ucrt\assert.h:12:
C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\ucrt\corecrt.h:610:16: error: redefinition of '__crt_locale_data_public'
typedef struct __crt_locale_data_public
               ^
C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt\corecrt.h:596:16: note: previous definition is here
typedef struct __crt_locale_data_public
               ^
In file included from input_line_3:38:
In file included from C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include\cassert:9:
In file included from C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\ucrt\assert.h:12:
C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\ucrt\corecrt.h:617:16: error: redefinition of '__crt_locale_pointers'
typedef struct __crt_locale_pointers
               ^
C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt\corecrt.h:603:16: note: previous definition is here
typedef struct __crt_locale_pointers
               ^
In file included from input_line_3:38:
In file included from C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include\cassert:9:
In file included from C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\ucrt\assert.h:12:
C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\ucrt\corecrt.h:625:16: error: redefinition of '_Mbstatet'
typedef struct _Mbstatet
               ^
C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt\corecrt.h:611:16: note: previous definition is here
typedef struct _Mbstatet
               ^
```

**Comment by wenjian-zhou** [comment]
> raise RuntimeError("could not load cppyy_backend library, details:\n%s" % RuntimeError: could not load cppyy_backend library, details: Could not find module 'libcppyy_backend.cp38-win_amd64.pyd' (or one of its dependencies). Try using the full path with constructor syntax. [WinError 1114] 动态链接库(DLL)初始化例程失败。 Could not find module 'libcppyy_backend.dll' (or one of its dependencies). Try using the full path with constructor syntax. Could not find module 'C:\GIT\mymeep\venv\lib\site-packages\cppyy_backend\lib\libcppyy_backend.cp38-win_amd64.pyd' (or one of its dependencies). Try using the full path with constructor syntax. python-BaseException

@NiKeYiGuN Have you found a fix? I have the same issue as well.
